import { NextResponse } from "next/server";

export async function GET() {
  // For demo purposes, we'll create a simple HTML and return it as a download
  // In production, you'd use a library like pdf-lib or puppeteer
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Court-Admissible Intelligence Package</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid #333;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .section {
          margin: 20px 0;
          padding: 15px;
          border-left: 4px solid #ff003c;
          background-color: #f9f9f9;
        }
        .risk-high {
          color: #ff003c;
          font-weight: bold;
        }
        .footer {
          margin-top: 50px;
          text-align: center;
          font-size: 12px;
          color: #666;
          border-top: 1px solid #eee;
          padding-top: 20px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Court-Admissible Intelligence Package</h1>
        <p>Generated: ${new Date().toLocaleString()}</p>
        <p>Case: High-Risk Money Mule Cluster</p>
      </div>

      <div class="section">
        <h2>Summary</h2>
        <p>Identified coordinated transfers between multiple accounts with high risk scores, indicative of a money mule network.</p>
      </div>

      <div class="section">
        <h2>Risk Assessment</h2>
        <p>Overall Risk: <span class="risk-high">CRITICAL</span></p>
        <p>Entities Involved: 11</p>
        <p>Flagged Transfers: 8</p>
      </div>

      <div class="section">
        <h2>Key Findings</h2>
        <ul>
          <li>Central mule account receiving transfers from 4 victim accounts</li>
          <li>Common device (iPhone 15 Pro) linked to multiple high-risk entities</li>
          <li>Transfers to offshore holding account</li>
        </ul>
      </div>

      <div class="footer">
        <p>This document is for investigative purposes only.</p>
        <p>Generated by Et AI Digital Public Safety Platform</p>
      </div>
    </body>
    </html>
  `;

  // Return a response that tells the browser to download the HTML as a file
  // For real PDF generation, you'd use a library like @react-pdf/renderer or pdf-lib
  return new NextResponse(htmlContent, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="intelligence-package-${Date.now()}.html"`,
    },
  });
}
