"use client";

import React from "react";
import { motion } from "framer-motion";
import { X, Printer, ShieldAlert } from "lucide-react";

interface ReportGeneratorProps {
  source: "VoiceShield" | "PhishingDisassembler";
  threatLevel: number;
  data: any;
  onClose: () => void;
}

export default function ReportGenerator({ source, threatLevel, data, onClose }: ReportGeneratorProps) {
  const handlePrint = () => {
    window.print();
  };

  const currentDate = new Date().toLocaleString();
  const reportId = `NCRB-${Math.floor(100000 + Math.random() * 900000)}`;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm print:bg-white print:backdrop-blur-none p-4">
      {/* Non-printable Close Button */}
      <button 
        onClick={onClose}
        className="absolute top-6 right-6 p-2 bg-[#333] hover:bg-[#555] rounded-full text-white print:hidden transition-colors"
      >
        <X className="w-6 h-6" />
      </button>

      {/* The Printable Report Container */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white text-black w-full max-w-3xl max-h-[90vh] overflow-y-auto print:max-h-none print:overflow-visible rounded-lg shadow-2xl p-8 md:p-12"
      >
        {/* Header */}
        <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-6">
          <div className="flex items-center gap-3">
            <ShieldAlert className="w-12 h-12 text-black" />
            <div>
              <h1 className="text-2xl font-bold font-serif uppercase tracking-widest">Incident Report</h1>
              <h2 className="text-sm font-bold uppercase tracking-wider text-gray-600">Digital Public Safety Command Center</h2>
            </div>
          </div>
          <div className="text-right font-mono text-xs text-gray-500">
            <p><strong>REPORT ID:</strong> {reportId}</p>
            <p><strong>DATE GENERATED:</strong> {currentDate}</p>
            <p><strong>SOURCE MODULE:</strong> {source}</p>
          </div>
        </div>

        {/* Threat Summary Section */}
        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4 uppercase">1. Threat Summary</h3>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-gray-100 p-4 rounded border border-gray-300">
              <p className="text-xs uppercase text-gray-500 font-bold">Compound Threat Level</p>
              <p className="text-3xl font-bold font-mono">{threatLevel}%</p>
            </div>
            <div className="bg-gray-100 p-4 rounded border border-gray-300">
              <p className="text-xs uppercase text-gray-500 font-bold">Automated Verdict</p>
              <p className="text-xl font-bold uppercase text-red-600 mt-1">
                {threatLevel >= 75 ? "CRITICAL THREAT DETECTED" : "ELEVATED RISK"}
              </p>
            </div>
          </div>
        </div>

        {/* Forensic Evidence Section */}
        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4 uppercase">2. Forensic Evidence Log</h3>
          
          {source === "VoiceShield" && (
            <div className="bg-gray-50 border border-gray-300 p-4 rounded text-sm font-mono whitespace-pre-wrap leading-relaxed">
              <strong>Captured Audio Transcript:</strong>
              <br/><br/>
              {data.transcript || "No transcript available."}
            </div>
          )}

          {source === "PhishingDisassembler" && (
            <div className="bg-gray-50 border border-gray-300 p-4 rounded text-sm font-mono whitespace-pre-wrap leading-relaxed">
              <strong>Extracted Payload:</strong>
              <br/><br/>
              {data.payload || "No payload available."}
              <br/><br/>
              <strong>Identified URL:</strong> {data.url || "None"}
              <br/>
              <strong>Domain Location:</strong> {data.location || "Unknown"}
            </div>
          )}
        </div>

        {/* AI Analysis Section */}
        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4 uppercase">3. Automated System Analysis</h3>
          <div className="bg-red-50 border border-red-200 p-4 rounded text-sm">
            <p className="font-bold text-red-700 mb-2">System Conclusion:</p>
            <p className="text-red-900">{data.summary || "This activity exhibits high-probability markers of organized fraud."}</p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-gray-300 text-center text-xs text-gray-500 font-mono">
          <p>This report was auto-generated by the AI-Powered Threat Detection Suite.</p>
          <p>It is suitable for attachment to formal cybercrime complaints (e.g., cybercrime.gov.in).</p>
        </div>

        {/* Non-printable Action Button */}
        <div className="mt-8 flex justify-end print:hidden">
          <button 
            onClick={handlePrint}
            className="bg-black hover:bg-gray-800 text-white px-6 py-3 rounded-lg font-bold flex items-center gap-2 transition-colors"
          >
            <Printer className="w-5 h-5" />
            Print to PDF / Save
          </button>
        </div>
      </motion.div>
    </div>
  );
}
